version: '3.7'

services:

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - theater-container

  mailserver:
    image: mailserver/docker-mailserver:10.2.0
    hostname: theater.csail.mit.edu
    domainname: theater.csail.mit.edu
    volumes:
      - ./config/postfix-accounts.cf:/tmp/docker-mailserver/postfix-accounts.cf
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 25
    env_file: config/mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  redis:
    image: redis:6.2.3-alpine
    environment:
      - REDIS_APPENDONLY=yes

  theater-container:
    build: .
    expose:
      - 80
    volumes:
      - ./app:/mount/theater
      - ./www:/mount/www
    env_file: config/theater.env
    depends_on:
      - mailserver
      - redis
