version: '3.8'

services:

  graffiti-auth:
    environment:
      DEBUG: 'true'
      DOMAIN: 'localhost:5000'
      AUTH_SECRET: 'secret'

  graffiti-app:
    environment:
      DEBUG: 'true'
      AUTH_SECRET: 'secret'

  nginx:
    volumes:
      - ./config/nginx/debug.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:5000
