version: '3.7'

services:

  redis:
    image: redis:6.2.3-alpine
    environment:
      REDIS_APPENDONLY: 'yes'

  theater-container:
    build: .
    volumes:
      - ./app:/mount/theater
      - ./www:/mount/www
      - ./js:/mount/js
    environment:
      DEBUG: 'true'
      ATTEND_WS_INTERVAL: '5000' # milliseconds
      ATTEND_WS_ACTIONS_PER_MESSAGE: '10'
      SECRET: 'secret'
    depends_on:
      - redis
