version: '3.8'

services:

  graffiti-container:
    build: .
    volumes:
      - ./app:/mount/graffiti
    environment:
      SECRET: 'secret'
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    image: mongo:5.0.6
    volumes:
      - ./db:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    image: mongo:5.0.6
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    image: mongo:5.0.6
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
