version: '3.8'

services:

  nginx:
    volumes:
      - ./config/nginx/deploy.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    ports:
      - 80:80
      - 443:443

  mailserver:
    image: mailserver/docker-mailserver:11.0.0
    container_name: graffiti-mailserver
    hostname: ${DOMAIN}
    domainname: ${DOMAIN}
    volumes:
      - ./config/mailserver:/tmp/docker-mailserver/
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/ssl/certs/privkey.pem:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 25
    env_file: config/mailserver.env
    environment:
      - POSTMASTER_ADDRESS=${POSTMASTER}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  graffiti-auth:
    environment:
      DEBUG: 'false'
      DOMAIN: ${DOMAIN}
    depends_on:
      - mailserver

  graffiti-app:
    environment:
      DEBUG: 'false'
