version: '3.7'

services:

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - graffiti

  mailserver:
    image: mailserver/docker-mailserver:10.2.0
    hostname: theater.csail.mit.edu
    domainname: theater.csail.mit.edu
    volumes:
      - ./config/mailserver:/tmp/docker-mailserver/
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 25
    env_file: config/mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  theater-container:
    environment:
      DEBUG: 'false'
      AUTH_CODE_MAIL_FROM: 'Graffiti <noreply@graffiti.csail.mit.edu>'
    expose:
      - 80
    depends_on:
      - mailserver
