version: '3.8'

services:

  graffiti:
    build: .
    volumes:
      - ./app:/mount/graffiti
    environment:
      AUTH_SECRET: 'secret'
      AUTH_CODE_SIZE: '6'
      AUTH_CODE_EXP_TIME: '5' # minutes
      QUERY_HEARTBEAT: '5'
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6
    restart: always
    container_name: mongo
    hostname: mongo
    volumes:
      - ./db:/data/db
    command: "--bind_ip_all --replSet rs0 --quiet --logpath /dev/null"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
