version: '3.8'

services:

  graffiti-auth:
    container_name: graffiti-auth
    build: auth
    volumes:
      - ./auth:/mount/auth
    environment:
      AUTH_CODE_EXP_TIME: 5 # minutes

  graffiti-app:
    container_name: graffiti-app
    build: app
    volumes:
      - ./app:/mount/app
    depends_on:
      - mongo
      - redis
    environment:
      BATCH_SIZE: 100

  graffiti-broker:
    container_name: graffiti-broker
    build: broker
    volumes:
      - ./broker:/mount/broker
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.21.6
    container_name: graffiti-nginx
    volumes:
      - ./config/nginx/base.conf:/etc/nginx/base.conf:ro

  mongo:
    image: mongo:5.0.9
    container_name: graffiti-mongo
    restart: always
    volumes:
      - ./db:/data/db

  redis:
    image: redis:7.0.0
    container_name: graffiti-redis
