version: '3.8'

services:

  graffiti-auth:
    container_name: graffiti-auth
    build: auth
    volumes:
      - ./auth:/mount/auth
    environment:
      AUTH_CODE_EXP_TIME: 5 # minutes

  graffiti-app:
    container_name: graffiti-app
    build: app
    volumes:
      - ./app:/mount/app
    depends_on:
      - mongo
    environment:
      BATCH_SIZE: 100

  nginx:
    image: nginx:1.23.3
    container_name: graffiti-nginx
    volumes:
      - ./config/nginx/base.conf:/etc/nginx/templates/base.conf.template:ro

  mongo:
    image: mongo:6.0.3-focal
    container_name: graffiti-mongo
    restart: always
    volumes:
      - ./db:/data/db
