version: '3.8'

services:

  graffiti:
    build: .
    volumes:
      - ./app:/mount/graffiti
    environment:
      SECRET: 'secret'
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6
    volumes:
      - ./db:/data/db
    command: mongod --bind_ip_all --replSet rs0 --quiet --logpath /dev/null
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
