version: '3.8'

services:

  graffiti-auth:
    container_name: graffiti-auth
    build: auth
    volumes:
      - ./auth:/mount/auth
    environment:
      AUTH_SECRET: 'secret'
      AUTH_CODE_EXP_TIME: '5' # minutes

  mongo:
    image: mongo:5.0.6
    container_name: graffiti-mongo
    hostname: mongo
    restart: always
    volumes:
      - ./db:/data/db
