version: '2'
services:

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - 80:80
      - 443:443

  redis:
    image: redis:6.2.3-alpine
    environment:
      - REDIS_APPENDONLY=yes

  theater:
    build: .
    expose:
      - 80
    volumes:
      - .:/code
    depends_on:
      - redis
