version: '3.8'

services:

  graffiti:
    container_name: graffiti
    build: .
    volumes:
      - ./app:/mount/graffiti
    environment:
      AUTH_SECRET: 'secret'
      AUTH_CODE_SIZE: '6' # characters
      AUTH_CODE_EXP_TIME: '5' # minutes
      QUERY_HEARTBEAT: '5' # seconds
      QUERY_LIMIT: '100' # max number of items returned at once
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6
    container_name: graffiti-mongo
    hostname: mongo
    restart: always
    volumes:
      - ./db:/data/db
